terminal:
  image: node:slim
  # services:
  #   - name: registry.gitlab.com/gitlab-org/webide-file-sync:latest
  #     alias: webide-file-sync
  #     entrypoint: ["/bin/sh"]
  #     command: ["-c", "sleep 5 && ./webide-file-sync -port 4004 -project-dir $CI_PROJECT_DIR"]
  #     ports:
  #       - number: 4004
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
  script: sleep 60
  variables:
    NODE_ENV: "development"
